"""add positions table, staff position_id fk

Revision ID: 003
Revises: 002
Create Date: 2026-09-15 22:32:55.033705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_auth_accounts_status', 'auth_accounts', ['status'], unique=False)
    op.drop_index('idx_email_verifications_expires_at', table_name='email_verifications')
    op.drop_column('email_verifications', 'code_hash')
    op.drop_column('email_verifications', 'last_sent_at')
    op.drop_column('email_verifications', 'expires_at')
    op.drop_column('email_verifications', 'verified')
    op.drop_column('email_verifications', 'attempts')
    op.drop_constraint('positions_uuid_key', 'positions', type_='unique')
    op.drop_index('ix_positions_uuid', table_name='positions')
    op.create_index(op.f('ix_positions_uuid'), 'positions', ['uuid'], unique=True)
    op.add_column('staff', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_index('idx_staff_position_id', 'staff', ['position_id'], unique=False)
    op.create_foreign_key(None, 'staff', 'positions', ['position_id'], ['id'])
    op.drop_column('staff', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_index('idx_staff_position_id', table_name='staff')
    op.drop_column('staff', 'position_id')
    op.drop_index(op.f('ix_positions_uuid'), table_name='positions')
    op.create_index('ix_positions_uuid', 'positions', ['uuid'], unique=False)
    op.create_unique_constraint('positions_uuid_key', 'positions', ['uuid'])
    op.add_column('email_verifications', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('email_verifications', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('email_verifications', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('email_verifications', sa.Column('last_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('email_verifications', sa.Column('code_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index('idx_email_verifications_expires_at', 'email_verifications', ['expires_at'], unique=False)
    op.drop_index('idx_auth_accounts_status', table_name='auth_accounts')
    # ### end Alembic commands ###
