"""004_add attendance table

Revision ID: 004
Revises: 003
Create Date: 2026-09-16 02:47:14.425455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Guard this drop so it doesn't fail on databases where the column
    # was never created (e.g. fresh Neon/local databases).
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('auth_roles')]
    if 'is_super_admin' in columns:
        op.drop_column('auth_roles', 'is_super_admin')
    # ### NOTE: this migration is named "add attendance table" but does
    # not currently create one. See follow-up migration 005 for the
    # actual attendance table creation. ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_roles', sa.Column('is_super_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###