"""initial_schema

Revision ID: d215009f5e3c
Revises: 
Create Date: 2026-09-01 16:23:30.778765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd215009f5e3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('module', sa.String(length=255), nullable=False),
    sa.Column('group', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('codename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codename'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_permissions_codename', 'auth_permissions', ['codename'], unique=False)
    op.create_index('idx_permissions_module', 'auth_permissions', ['module'], unique=False)
    op.create_index(op.f('ix_auth_permissions_id'), 'auth_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_auth_permissions_uuid'), 'auth_permissions', ['uuid'], unique=True)
    op.create_table('auth_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_roles_name', 'auth_roles', ['name'], unique=False)
    op.create_index(op.f('ix_auth_roles_id'), 'auth_roles', ['id'], unique=False)
    op.create_index(op.f('ix_auth_roles_uuid'), 'auth_roles', ['uuid'], unique=True)
    op.create_table('auth_token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_token_blacklist_id'), 'auth_token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_auth_token_blacklist_jti'), 'auth_token_blacklist', ['jti'], unique=True)
    op.create_index(op.f('ix_auth_token_blacklist_uuid'), 'auth_token_blacklist', ['uuid'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_departments_name', 'departments', ['name'], unique=False)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_uuid'), 'departments', ['uuid'], unique=True)
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_email_verifications_email', 'email_verifications', ['email'], unique=False)
    op.create_index('idx_email_verifications_expires_at', 'email_verifications', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_verifications_id'), 'email_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_email_verifications_uuid'), 'email_verifications', ['uuid'], unique=True)
    op.create_table('auth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=191), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', name='admin_status_enum'), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_auth_accounts_email', 'auth_accounts', ['email'], unique=False)
    op.create_index('idx_auth_accounts_status', 'auth_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_auth_accounts_email'), 'auth_accounts', ['email'], unique=True)
    op.create_index(op.f('ix_auth_accounts_id'), 'auth_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_auth_accounts_uuid'), 'auth_accounts', ['uuid'], unique=True)
    op.create_table('auth_role_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_role_permission_id'), 'auth_role_permission', ['id'], unique=False)
    op.create_index(op.f('ix_auth_role_permission_uuid'), 'auth_role_permission', ['uuid'], unique=True)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_LEAVE', 'TERMINATED', name='staff_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_staff_department_id', 'staff', ['department_id'], unique=False)
    op.create_index('idx_staff_status', 'staff', ['status'], unique=False)
    op.create_index('idx_staff_user_id', 'staff', ['user_id'], unique=False)
    op.create_index(op.f('ix_staff_id'), 'staff', ['id'], unique=False)
    op.create_index(op.f('ix_staff_uuid'), 'staff', ['uuid'], unique=True)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_attendance_date', 'attendance', ['date'], unique=False)
    op.create_index('idx_attendance_staff_date', 'attendance', ['staff_id', 'date'], unique=True)
    op.create_index('idx_attendance_staff_id', 'attendance', ['staff_id'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_uuid'), 'attendance', ['uuid'], unique=True)
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.Enum('ANNUAL', 'SICK', 'UNPAID', 'MATERNITY', 'PATERNITY', 'BEREAVEMENT', name='leave_type_enum'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leave_status_enum'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['auth_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_leave_requests_staff_id', 'leave_requests', ['staff_id'], unique=False)
    op.create_index('idx_leave_requests_staff_status', 'leave_requests', ['staff_id', 'status'], unique=False)
    op.create_index('idx_leave_requests_status', 'leave_requests', ['status'], unique=False)
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    op.create_index(op.f('ix_leave_requests_uuid'), 'leave_requests', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_requests_uuid'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_id'), table_name='leave_requests')
    op.drop_index('idx_leave_requests_status', table_name='leave_requests')
    op.drop_index('idx_leave_requests_staff_status', table_name='leave_requests')
    op.drop_index('idx_leave_requests_staff_id', table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_attendance_uuid'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_index('idx_attendance_staff_id', table_name='attendance')
    op.drop_index('idx_attendance_staff_date', table_name='attendance')
    op.drop_index('idx_attendance_date', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_staff_uuid'), table_name='staff')
    op.drop_index(op.f('ix_staff_id'), table_name='staff')
    op.drop_index('idx_staff_user_id', table_name='staff')
    op.drop_index('idx_staff_status', table_name='staff')
    op.drop_index('idx_staff_department_id', table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_auth_role_permission_uuid'), table_name='auth_role_permission')
    op.drop_index(op.f('ix_auth_role_permission_id'), table_name='auth_role_permission')
    op.drop_table('auth_role_permission')
    op.drop_index(op.f('ix_auth_accounts_uuid'), table_name='auth_accounts')
    op.drop_index(op.f('ix_auth_accounts_id'), table_name='auth_accounts')
    op.drop_index(op.f('ix_auth_accounts_email'), table_name='auth_accounts')
    op.drop_index('idx_auth_accounts_status', table_name='auth_accounts')
    op.drop_index('idx_auth_accounts_email', table_name='auth_accounts')
    op.drop_table('auth_accounts')
    op.drop_index(op.f('ix_email_verifications_uuid'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_id'), table_name='email_verifications')
    op.drop_index('idx_email_verifications_expires_at', table_name='email_verifications')
    op.drop_index('idx_email_verifications_email', table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_departments_uuid'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index('idx_departments_name', table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_auth_token_blacklist_uuid'), table_name='auth_token_blacklist')
    op.drop_index(op.f('ix_auth_token_blacklist_jti'), table_name='auth_token_blacklist')
    op.drop_index(op.f('ix_auth_token_blacklist_id'), table_name='auth_token_blacklist')
    op.drop_table('auth_token_blacklist')
    op.drop_index(op.f('ix_auth_roles_uuid'), table_name='auth_roles')
    op.drop_index(op.f('ix_auth_roles_id'), table_name='auth_roles')
    op.drop_index('idx_roles_name', table_name='auth_roles')
    op.drop_table('auth_roles')
    op.drop_index(op.f('ix_auth_permissions_uuid'), table_name='auth_permissions')
    op.drop_index(op.f('ix_auth_permissions_id'), table_name='auth_permissions')
    op.drop_index('idx_permissions_module', table_name='auth_permissions')
    op.drop_index('idx_permissions_codename', table_name='auth_permissions')
    op.drop_table('auth_permissions')
    # ### end Alembic commands ###
